# frozen_string_literal: true

source "https://rubygems.org"

gem 'redis-namespace'
gem 'http'  # exercises dependency on libffi
gem 'psych' # exercises dependency on libyaml

group :development do
  gem 'rspec-core'
  gem 'nio4r'
end
